### ISSUE TITLE
TODO: Looking for frontend design for home page, share your designs here. 

### ISSUE THREAD

**Issue by PaulBratslavsky** [PaulBratslavsky/nextjs-build-in-public#11]
Here are some inspirations I was looking at.  Which one would you like to base our design on  1 or 2.  Or recommend a design. 

1. [MiExpo](http://preview.themeforest.net/item/miexpo-event-conference-html-template/full_screen_preview/25251151?_ga=2.248864002.467238336.1697644023-1342033901.1670708803&_gac=1.229570926.1696799724.Cj0KCQjwpompBhDZARIsAFD_Fp9DEEk3ZMqV081UXV1y94GUuiFSCtIv9fD9_Q1TcO3dq-rgvme9G0gaAh40EALw_wcB)

2. [Eventum](https://preview.themeforest.net/item/eventum-event-conference-html-template/full_screen_preview/46309238?_ga=2.248864002.467238336.1697644023-1342033901.1670708803&_gac=1.229570926.1696799724.Cj0KCQjwpompBhDZARIsAFD_Fp9DEEk3ZMqV081UXV1y94GUuiFSCtIv9fD9_Q1TcO3dq-rgvme9G0gaAh40EALw_wcB)

Requirements: 

Navigation
  - logo
  - home link
  - events
  - signup link

Hero section: 
  - heading
  - text
  - image
  - button to sign up

Events List: ( showing top 5 upcoming events )
 - event card
   - event name
   - event description
   - event date and start time
   - event location address
   - event created by

**Comment by ztxone** [comment]
I vote for 2nd one - Eventum. But i've also try to create by-my-view logo and name before i had red this issue actually LOL ))

**Comment by ztxone** [comment]
Are you planning to copy the entire design or just look at the blocks from this template?

**Comment by PaulBratslavsky** [comment]
Nice.  Awesome.  I saw also what you have done in the following PR and was merged into main code https://github.com/PaulBratslavsky/nextjs-build-in-public/pull/23 

I think only going for just the pieces we need.  What you have done on the home page looks wonderful.  
The only piece that is left to make the home page complete, is to create the Events cards to show the upcoming events.

**Comment by PaulBratslavsky** [comment]
Yes. Let's continue with this option.  [Eventum](https://preview.themeforest.net/item/eventum-event-conference-html-template/full_screen_preview/46309238?_ga=2.248864002.467238336.1697644023-1342033901.1670708803&_gac=1.229570926.1696799724.Cj0KCQjwpompBhDZARIsAFD_Fp9DEEk3ZMqV081UXV1y94GUuiFSCtIv9fD9_Q1TcO3dq-rgvme9G0gaAh40EALw_wcB)

Next needed components:

Event card: 
<img width="1278" alt="Screenshot 2023-10-23 at 2 09 54 AM" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/6153188/266694c7-7387-471e-ae1c-7380369185d8">


Login And Register Forms: [example](https://preview.themeforest.net/item/eventum-event-conference-html-template/full_screen_preview/46309238?_ga=2.248864002.467238336.1697644023-1342033901.1670708803&_gac=1.229570926.1696799724.Cj0KCQjwpompBhDZARIsAFD_Fp9DEEk3ZMqV081UXV1y94GUuiFSCtIv9fD9_Q1TcO3dq-rgvme9G0gaAh40EALw_wcB)

<img width="1249" alt="Screenshot 2023-10-23 at 2 11 44 AM" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/6153188/754763ca-4b1f-497e-93d8-2b5f14145daa">

Singel Event Page: https://preview.themeforest.net/item/eventum-event-conference-html-template/full_screen_preview/46309238?_ga=2.248864002.467238336.1697644023-1342033901.1670708803&_gac=1.229570926.1696799724.Cj0KCQjwpompBhDZARIsAFD_Fp9DEEk3ZMqV081UXV1y94GUuiFSCtIv9fD9_Q1TcO3dq-rgvme9G0gaAh40EALw_wcB

<img width="1247" alt="Screenshot 2023-10-23 at 2 12 43 AM" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/6153188/33c2aab1-7568-4346-91cd-069256e15015">

We are making progress.  yay.

**Comment by ztxone** [comment]
i've done one else section. For Home page, i think. Instead of Hero section may be...
<img width="1449" alt="Screenshot 2023-10-23 at 11 40 11" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/39146381/a9507b77-01ef-4176-a922-b77654c36f9a">
and then below that will be list of events

But i couldn't make another PR while first one wasn't merged... Is it normal behaviour?

**Comment by ztxone** [comment]
BTW to my mind Eventum looks too pinky...
I suggest this color scheme up to Logo colors 

![Screenshot 2023-10-21 at 14 04 42](https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/39146381/b6e80604-d071-4aab-b2c4-86cf5117cfcc)

**Comment by PaulBratslavsky** [comment]
@ztxone love the colors, lets do it.  In terms of commits. I would focus on one pull request just to make it easier to manage.  And you can do as many changes in a single pull request as you need.

I am also still trying to get better at managing public repos with multiple contributors, so thank you for your patience.

I think next step is working on the following issues 

https://github.com/PaulBratslavsky/nextjs-build-in-public/issues/30
https://github.com/PaulBratslavsky/nextjs-build-in-public/issues/18
https://github.com/PaulBratslavsky/nextjs-build-in-public/issues/17
https://github.com/PaulBratslavsky/nextjs-build-in-public/issues/20
