### ISSUE TITLE
TODO: CREATE SINGLE EVENT DETAILS PAGE

### ISSUE THREAD

**Issue by PaulBratslavsky** [PaulBratslavsky/nextjs-build-in-public#20]
Create Single Event Page

That will show the details of the event.

**Comment by PaulBratslavsky** [comment]
@ztxone you are doing awesome. Great job an the cards.  We can work on this page. Lets make this static at first so use dummy data.  And once the ui is done, I will fetch the data and make dynamic.  

![2023-10-25_11-16-41](https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/6153188/f38186f2-f9af-42d7-87cb-05bbf01ae1b5)

**Comment by ztxone** [comment]
Done) I think it looks good!

**Comment by PaulBratslavsky** [comment]
@ztxone it looks amazing.  You are awesome. Merged.
https://github.com/PaulBratslavsky/nextjs-build-in-public/pull/45
