### ISSUE TITLE
TODO: ADD REMOVE EVENTS BUTTON SHOULD BE SOFT DELETE

### ISSUE THREAD

**Issue by PaulBratslavsky** [PaulBratslavsky/nextjs-build-in-public#58]
Instead of completely removing past events.  We should have the `archived` or `removed` Boolean type.

**Comment by ztxone** [comment]
Made ui for it on Dashboard events page - buttons for moving to archived and back. And separate table of passed or archived events. Check PR, please

**Comment by PaulBratslavsky** [comment]
Looks good i added soft delete and recover functionality. https://github.com/PaulBratslavsky/nextjs-build-in-public/pull/68
